twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        titre: 'Titre test'
        users: ['David', 'Morgane', 'Tom', 'Owein', 'Oona']

when@test:
    twig:
        strict_variables: true
